"""Single source of truth (SSOT) for the ``ov`` artifact schema.

One Pydantic v2 model tree defines *what a capture is* and *what an analysis
produces*. Every other module reads from these models rather than inventing its
own shapes -- this is the SSOT discipline from the build specification (§3.3).

The tree has four families:

* **Operate value types** -- :class:`Action`, :class:`Affordance`,
  :class:`Observation`, :class:`ActionResult`, :class:`ProgressSignal`. These
  are the deterministic, model-free currency of the ``operate/`` "hands".
* **Capture artifacts** -- :class:`Artifact`, :class:`JourneyStep`,
  :class:`CaptureRun`. What a browser session records.
* **Inferred facts** -- :class:`Scored`, :class:`TechFinding`,
  :class:`Endpoint`. Probabilistic conclusions that always carry confidence and
  provenance (D2: outputs are never ground truth).
* **Analysis outputs** -- :class:`Evidence`, :class:`Severity`,
  :class:`Finding`, :class:`EvidenceBundle`. The normalized currency of the
  analysis lenses and the grounded LLM layer (D3 + D4).

Design notes
------------
* IDs are generated by :func:`new_id` (prefix + short uuid) so artifacts and
  findings are addressable and joinable across the store.
* ``confidence`` appears twice on purpose, matching the spec: :class:`Scored`
  uses an integer 0-100 (Wappalyzer-style) for *detected technologies*;
  :class:`Finding` carries a float 0-1 for *analysis judgments*.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

# --------------------------------------------------------------------------- #
# Identity helpers
# --------------------------------------------------------------------------- #


def new_id(prefix: str = "id") -> str:
    """Return a short, unique, prefixed id, e.g. ``"step_3f9a1c2b"``.

    >>> i = new_id("run")
    >>> i.startswith("run_")
    True
    >>> len(new_id("x").split("_")[1])
    8
    """
    return f"{prefix}_{uuid.uuid4().hex[:8]}"


def utcnow() -> datetime:
    """Timezone-aware current UTC time (the project's canonical timestamp)."""
    return datetime.now(timezone.utc)


# --------------------------------------------------------------------------- #
# Operate value types -- the model-free currency of the "hands"
# --------------------------------------------------------------------------- #

ActionType = Literal["click", "type", "select", "navigate", "key", "scroll", "wait"]


class Action(BaseModel):
    """A single deterministic operation against the target.

    Mirrors Playwright-MCP's require-description-and-ref safety: actions that
    touch an element carry a ``ref`` (a stable affordance handle) *and* a human
    ``description`` so the journal records intent legibly.
    """

    type: ActionType
    ref: str | None = None  # affordance ref (e.g. "e7") for click/type/select
    description: str | None = None  # human-readable target description
    text: str | None = None  # for type
    url: str | None = None  # for navigate
    key: str | None = None  # for key
    value: str | list[str] | None = None  # for select
    args: dict[str, Any] = Field(default_factory=dict)  # scroll deltas, etc.


class Affordance(BaseModel):
    """One actionable element as perceived by a perception strategy.

    ``bbox`` is ``(x, y, w, h)`` in CSS pixels when a strategy can compute it
    (always for Screenshot/Hybrid, optional for pure AX snapshots).
    """

    ref: str
    role: str
    name: str = ""
    bbox: tuple[float, float, float, float] | None = None
    enabled: bool = True
    editable: bool = False


class Observation(BaseModel):
    """The uniform result of any perception strategy (a pure read).

    ``obs_hash`` is a content hash of the salient observable state; it is what
    :class:`ProgressSignal` uses to detect no-progress without an LLM.
    """

    strategy: str  # "ax_snapshot" | "screenshot" | "hybrid"
    url: str | None = None
    affordances: list[Affordance] = Field(default_factory=list)
    aria_snapshot: str | None = None  # YAML-ish ref-bearing tree (mode="ai")
    screenshot_artifact_id: str | None = None
    obs_hash: str = ""
    title: str | None = None
    t_ms: float = 0.0


class ActionResult(BaseModel):
    """Outcome of :func:`ov.operate.act.act` -- success/error *plus* a fresh read.

    The fresh :class:`Observation` is the contract that lets the host (policy
    layer) decide the next step without a second explicit observe call.
    """

    action: Action
    ok: bool
    error: str | None = None
    observation: Observation | None = None
    t_ms: float = 0.0


class ProgressSignal(BaseModel):
    """Deterministic loop / no-progress *facts* (the package never decides to stop).

    The host (policy layer) interprets these against its budgets. See §2.3: "the
    package detects and reports no-progress; the host decides to abort."
    """

    repeated_action: bool = False  # last (tool, args_hash) seen before
    no_new_signal_steps: int = 0  # consecutive steps with unchanged obs_hash
    url_stasis: bool = False
    ax_stasis: bool = False
    repeated_error: bool = False
    loop_suspected: bool = False  # rolled-up advisory flag
    detail: dict[str, Any] = Field(default_factory=dict)


# --------------------------------------------------------------------------- #
# Capture artifacts
# --------------------------------------------------------------------------- #


class Artifact(BaseModel):
    """A content-addressed blob in the store, referenced by id everywhere else."""

    artifact_id: str = Field(default_factory=lambda: new_id("art"))
    kind: str  # "screenshot" | "dom" | "request" | "ax_tree" | "sse" | ...
    step_id: str | None = None
    uri: str = ""  # content-addressed path within the artifacts store
    content_hash: str | None = None
    content_type: str | None = None
    size: int | None = None
    meta: dict[str, Any] = Field(default_factory=dict)


class JourneyStep(BaseModel):
    """One recorded step of the user journey -- doubles as UX evidence (§2.3)."""

    id: str = Field(default_factory=lambda: new_id("step"))
    intent: str = ""  # enumerate | advance | replay (+free text)
    action: Action | None = None
    affordances_seen: list[Affordance] = Field(default_factory=list)
    outcome: Literal["ok", "blocked", "error", "noop"] = "ok"
    artifact_ids: list[str] = Field(default_factory=list)
    pre_obs_hash: str | None = None
    post_obs_hash: str | None = None
    network_delta: int = 0  # new requests since previous step
    console_delta: int = 0  # new console entries since previous step
    note: str | None = None
    t_ms: float = 0.0


# --------------------------------------------------------------------------- #
# Inferred facts -- always Scored (D2: probabilistic, never ground truth)
# --------------------------------------------------------------------------- #


class Scored(BaseModel):
    """Mixin for every inferred (non-observed) fact.

    Map-backed reconstructions must rank above name-lost (un-mapped) ones; that
    ordering is expressed through ``confidence`` + ``provenance``.
    """

    confidence: int = 50  # 0-100 (Wappalyzer-style)
    provenance: list[str] = Field(default_factory=list)  # artifact/journey ids


class TechFinding(Scored):
    """One detected technology (framework, library, CDN, analytics, hosting)."""

    name: str
    categories: list[str] = Field(default_factory=list)
    version: str | None = None


class Endpoint(Scored):
    """One synthesized API endpoint, with GenSON-merged request/response schemas."""

    method: str
    path_template: str
    kind: Literal["rest", "rpc", "graphql"] = "rest"
    request_schema: dict[str, Any] | None = None
    response_schema: dict[str, Any] | None = None
    auth: str | None = None  # bearer | cookie | oauth | api-key | None
    coverage: dict[str, Any] = Field(default_factory=dict)  # samples, statuses


# --------------------------------------------------------------------------- #
# Analysis outputs -- the normalized currency (D3 severity, D4 grounding)
# --------------------------------------------------------------------------- #


class Evidence(BaseModel):
    """The addressable unit an LLM claim must cite (D4).

    The model is shown the derived ``summary`` (a fact, not raw bytes); the
    ``artifact_id`` resolves -- via a lookup tool -- to the screenshot crop,
    network record or metric, for just-in-time retrieval during verification.
    """

    evidence_id: str = Field(default_factory=lambda: new_id("ev"))
    kind: Literal["mark", "network", "stack", "metric", "dom", "trace"]
    artifact_id: str | None = None
    summary: str = ""
    meta: dict[str, Any] = Field(default_factory=dict)


class Severity(BaseModel):
    """D3: ``severity = impact_tier x reach`` (prioritizes high-reach over rare-critical)."""

    impact_tier: str  # a11y: minor|moderate|serious|critical ; ux: "0".."4"
    reach: dict[str, Any] = Field(default_factory=dict)  # nodes, states, fraction
    score: float = 0.0


class Finding(BaseModel):
    """SSOT for every UX / a11y / perf / arch / robustness finding (D3 + D4).

    The hard fact/judgment split lives here: ``evidence_refs`` are *cited*
    (never authored by a model), ``judgment`` is model interpretation only. A
    finding with no resolvable evidence is rejected (cite-or-abstain); the
    honest "can't tell from the evidence" outcome is ``type="undetermined"``.
    """

    finding_id: str = Field(default_factory=lambda: new_id("find"))
    type: Literal[
        "ux_issue", "arch_fact", "interaction_pattern", "risk", "undetermined"
    ]
    signal: str  # catalog key, e.g. "contrast.text", "form.friction"
    category: Literal["a11y", "ux", "performance", "robustness", "architecture"]
    title: str = ""
    wcag_criterion: dict[str, Any] | None = None  # {id: "1.4.3", level: "AA"}
    heuristic: str | None = None  # "nielsen-1" | "cw-q3" | None
    engine_rule_id: str | None = None  # "axe:color-contrast" | "ibm:<id>"
    severity: Severity | None = None
    evidence_refs: list[str] = Field(default_factory=list)  # Evidence ids
    judgment: str | None = None  # model interpretation ONLY
    location: dict[str, Any] | None = None  # {state_id, url_or_route, selector...}
    observed: str = ""  # what the deterministic signal detected
    metric_detail: dict[str, Any] | None = None  # CWV value/threshold/phases
    suggested_fix: str | None = None  # grounded
    source_layer: Literal["deterministic", "llm"] = "deterministic"
    confidence: float = 1.0
    needs_human_review: bool = False
    diff_status: Literal["new", "changed", "resolved"] | None = None


class EvidenceBundle(BaseModel):
    """The grounded bundle a vision LLM reasons over (assembled model-free; §8.1).

    Layout contract: ``[role/system + cite-or-abstain] -> [marked image(s)] ->
    [facts keyed to mark/fact ids] -> [task last]``. Token cost is *computed*
    (``token_budget``), not hoped for.
    """

    step_id: str | None = None
    contract: str = ""  # the cite-or-abstain system/role text
    marked_image_artifact_ids: list[str] = Field(default_factory=list)
    crop_artifact_ids: list[str] = Field(default_factory=list)
    facts: list[Evidence] = Field(default_factory=list)
    marks: dict[str, str] = Field(default_factory=dict)  # mark_id -> evidence_id
    token_budget: dict[str, Any] = Field(default_factory=dict)
    task: str = ""


# --------------------------------------------------------------------------- #
# The run -- top of the tree
# --------------------------------------------------------------------------- #


class CaptureRun(BaseModel):
    """Everything one ``observe`` produced; artifacts live in the store by id."""

    model_config = ConfigDict(validate_assignment=False)

    run_id: str = Field(default_factory=lambda: new_id("run"))
    target_url: str = ""
    mode: Literal["reconstruct", "review"] = "reconstruct"
    started_at: datetime = Field(default_factory=utcnow)
    finished_at: datetime | None = None
    steps: list[JourneyStep] = Field(default_factory=list)
    artifacts: list[Artifact] = Field(default_factory=list)
    fingerprint: list[TechFinding] = Field(default_factory=list)
    rendering_model: str | None = None  # csr | ssr | ssg | streaming-ssr
    source_maps_present: bool | None = None  # the decisive reconstruction lever (D2)
    api_surface: list[Endpoint] = Field(default_factory=list)
    findings: list[Finding] = Field(default_factory=list)
    settings_snapshot: dict[str, Any] = Field(default_factory=dict)
    notes: list[str] = Field(default_factory=list)

    def artifact_by_id(self, artifact_id: str) -> Artifact | None:
        """Return the :class:`Artifact` with ``artifact_id`` or ``None``."""
        return next((a for a in self.artifacts if a.artifact_id == artifact_id), None)
